### ISSUE TITLE
Recent Stories view breaks sometimes in portrait/list view

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/ios-search-and-stories#131] opened 2015-10-12 18:50 UTC
When I go to my recent stories view I occasionally get this:

![img_5359](https://cloud.githubusercontent.com/assets/7061920/10435845/6f135ab2-70d7-11e5-8c68-6d405a49e50d.png)

When I close the app and restart it it corrects itself.

**Comment by chrismorast** [comment] 2015-10-22 15:28
Hey @sreilly , have you looked into this at all?

**Comment by sreilly** [comment] 2015-10-22 15:31
@chrismorast yes, but not found a solution (nor a reliable way to reproduce it) yet.  Was out of commission for the first part of this week but will get this fixed up now.

**Comment by sreilly** [comment] 2015-10-23 10:54
@chrismorast @thm I believe the current build should now fix this.  I'm not 100% confident that this will fix it because I wasn't always able to reproduce the problem, but I haven't been able to reproduce it after making this morning's change which _should_ have had an effect.

**Comment by thm** [comment] 2015-10-26 17:06
@sreilly thanks, @chrismorast can you confirm this is fixed? I'm not able to reproduce the issue.

**Comment by chrismorast** [comment] 2015-10-29 18:23
This is not fixed. I was testing other tabs and different orientations (portrait and landscape) to see if the feed position issue was fixed. Then I clicked on the recents tab and got this...
![img_5551](https://cloud.githubusercontent.com/assets/7061920/10828027/6a1a139c-7e2f-11e5-9cc3-96043df2107e.PNG)

**Comment by chrismorast** [comment] 2015-10-29 18:26
![img_5552](https://cloud.githubusercontent.com/assets/7061920/10828111/d9092ee6-7e2f-11e5-9dec-6f95c99030ec.PNG)

**Comment by chrismorast** [comment] 2015-10-29 18:27
The only way to fix is to close the app out entirely and reopen.

**Comment by sreilly** [comment] 2015-10-30 00:19
@chrismorast fixed it!  I still don't know how it was possible, but I've added a workaround.  The latest build (701) also overrides the system scroll position adjustment upon rotation, which I think is an improvement.

@thm mind if I push this one to testflight and submit to the app store?

**Comment by sreilly** [comment] 2015-10-30 01:02
oh darn... I just got it to reoccur in 701.

**Comment by sreilly** [comment] 2015-10-30 01:11
@thm @chrismorast ok, this should actually be fixed in 702.  Unfortunately I already pushed 701 to beta testers via testflight.  If this one works in the internal testflight then I'll push 702 to the public and the app store.  Sorry about the confusion and the extra beta notifications!

**Comment by thm** [comment] 2015-10-30 13:21
@sreilly I've installed 702 through TestFlight and I just saw this bug for the first time, I've never been able to reproduce it before:

![photo 30-10-15 2 16 06 pm](https://cloud.githubusercontent.com/assets/1379822/10846631/616dab9a-7f11-11e5-9b2c-66919bb86d0e.png)

**Comment by sreilly** [comment] 2015-10-30 13:25
@thm argh!  Yeah, I see it again now too.  This one is persistent!

**Comment by sreilly** [comment] 2015-10-30 13:27
It seems to occur when opening a certain type of story from the main stories view and then switching over to the recents list.

**Comment by sreilly** [comment] 2015-10-30 16:56
@thm I've just pushed a commit which should fix the root problem here.  Whenever there was an update to the underlying data all views would get a notification of the change, even if they weren't visible.  This means that the recent-stories view receives update notifications every time a story was marked as read, such as when you opened a new story in the main stories view.  The problem was that the UICollectionView that was being told about the update wasn't paying attention to changes if it wasn't actually visible, causing it to get out of sync with the data model.  That was bad, and was causing the layout problems and possibly some other unseen underlying issues.  Anyway, I do think this latest change will be the last necessary fix!

**Closed as completed** 2015-11-03 14:18 UTC
Labels: Bug, SHOW-STOPPER
