### ISSUE TITLE
Refresh stories spinner should be behind stories, not in front.

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#133] opened 2015-10-13 19:20 UTC

**Comment by thm** [comment] 2015-10-13 20:08
@nilnilnil Thanks, but this is a duplicate of #82. I've mentioned this issue a while ago but moved it to the 'iteration 1' milestone

**Comment by nilnilnil** [comment] 2015-10-13 20:09
@thm cool thanks. I didn't look through them all, sorry!

**Closed as completed by thm** 2015-10-13 20:08 UTC
Labels: Bug
