### ISSUE TITLE
No zoom-out available when viewing images from story feed 

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/ios-search-and-stories#93] opened 2015-09-15 23:39 UTC
I use to be able to zoom out and view the entire image (fit to width of screen) but now I can't zoom-out beyond 100% of the image size it seems.

**Comment by thm** [comment] 2016-01-11 22:27
@chrismorast if you still see this issue happen, can you take a screenshot? I'm unable to reproduce the issue.

**Comment by SwiftlyDeft** [comment] 2016-01-12 02:50
![img_3581](https://cloud.githubusercontent.com/assets/4774399/12253317/db901400-b943-11e5-997b-faeace79b785.PNG)
@thm & @chrismorast. To reproduce this "issue" you'll need to open a reddit link with a big image, i opened this one yesterday. Now the problem has to do with html tags being returned. It's not fitting on to the screen, thus the user can't pinch zoom it etc. After some testing i managed to figure out a way to take the src attribute then inject html into the web view that contains the right style attributes. Still testing this on a seperate project but will inform you once it's done.

**Comment by SwiftlyDeft** [comment] 2016-01-12 02:52
@thm, @chrismorast . By the way, if you open up that link in Safari, its all good, you can pinch zoom etc, make it fit on the screen. But if you use a UIWebView in a new project and load that image, it does not do whats expected. I suspect that Safari deal's with single images like these and makes a special case for them.

**Comment by chrismorast** [comment] 2016-02-03 18:54
Hey @SwiftlyDeft , sorry for the delay. I'm still unable to install hockeyapp build for some reason so I'm unable to test. Have you successfully tested the fix on your device?

**Comment by SwiftlyDeft** [comment] 2016-02-04 05:06
@chrismorast Does it install with an error, or gives you an error when installing the security certificates? Regarding this issue, it was due to the Web View just displaying the image. One option was to check if it was a single image and wrap some CSS styling around it. But then i realised that the updated Web View from Apple can do this automatically and add's performance update's to the normal stories and searches. It's working now, it fit's into the screen. Let us know what issues your facing with Hockey and i'll try and and get it fixed

**Comment by SwiftlyDeft** [comment] 2016-02-05 01:56
@chrismorast: If you ever get a chance to see this in action (when the build works for you!), try it out and let me know. Thanks

**Comment by chrismorast** [comment] 2016-04-19 15:44
👍 - works for me now in the new test flight build

**Comment by thm** [comment] 2016-04-19 15:54
Thanks @chrismorast @SwiftlyDeft, closing this

**Closed as completed by thm** 2016-04-19 15:54 UTC
Labels: Bug
